### ISSUE TITLE
Test cases made publicly available for system integrators to use on their projects

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#2440]
### Description

The Test Cases for OpenCRVS are hosted in the Test Rail software. As this is not publicly accessible we must create a public Google document Excel sheet that lists the test cases along with acceptance criteria.

### Acceptance criteria

GIVEN a test case exists in Test Rail
WHEN we review the Excel document
THEN we should see the test case title, user type associated and the acceptance criteria

### Tasks

- [x]  Copy all existing test cases from Test Rail to a Google Sheet with title, user type associated and acceptance criteria. - 5
- [x] Review sheet with Product Owner and itemise gaps that must be addressed & work with Antor to mark if the Test Case has an associated automated Cypress test - 3
- [ ] Make subsequent issues in Zenhub to ensure that Cypress automated tests coverage gradually increases 
- [ ] Make subsequent issues in Zenhub linked to this Epic to ensure that we can trace from requirements through to specific test cases to ensure that we are testing all functionality (including configuration requirements, NFRs etc.), via epics, designs, user stories etc.
- [ ] Work with Design team to improve the stories to include any requirements to fulfil the above task.
- [x] Mark if the Test Case is run on the Chrome browser and additionally share details of the tablet device used for testing the PWA
