### ISSUE TITLE
Create a "release management process" business process flow 

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#2443]
### Description

The QA team are required to run the full suite of test cases in advance of every release.  A process must be developed that allows the QA team time to perform this task and time for the development team to address issues.

The QA team must draft an example "release management process" business process flow that the team can adopt.  Then a calendar of releasing must be drafted to demonstrate how the time to complete the process can be managed.

### Tasks

- [ ] Draft an OpenCRVS release management process flow
- [ ] Review flow with Product Owner, design and technical team
- [ ] Draft an OpenCRVS release process example calendar
- [ ] Review calendar with Product Owner, design and technical team

Example ...

[RM Roll Out - Drafts.pdf](https://github.com/opencrvs/opencrvs-core/files/7845774/RM.Roll.Out.-.Drafts.pdf)
