### ISSUE TITLE
Form declaration updates

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2491]
### **Problem statement**

The current forms reflect the needs of Bangladesh but are not a good example of UN standard, rights-based civil registration that meet the basic needs of most countries.

### **Proposed work**

[Birth declaration](https://www.notion.so/Birth-declaration-04bdbc7b98a947cca54c7252423af2b1)

[Death application](https://www.notion.so/Death-application-ada99eb56011418b9a8e1cc30c8f519c)

We need to ensure that the UN standard is respected:

In the case of birth, the third revision of the Principles and Recommendations for a Vital Statistics System recommends, in paragraph 66, that the following information be collected:

- Date of occurrence of birth
- Date of registration
- Place of occurrence
- Place of registration
- Type of birth (single, twin or other)
- Attendant at birth
- Name of newborn
- Sex of newborn
- Weight of newborn
- Name of mother
- Date of birth of mother
- Marital status of mother
- Educational attainment of mother
- Place of usual residence (address) of mother
- Duration of residence at current address of mother
- Place or country of birth of mother
- Children born alive to mother during her entire lifetime
- Fetal deaths to mother during her lifetime
- Date of last previous birth by mother
- Date of marriage of mother
- Name of father
- Date of birth of father
- Marital status of father
- Education attainment of father
- Place of usual residence (address) of father

### Dependencies

(Other features which need to be complete for this work to be effective and fully testable)

### **Success criteria**

(The criteria that must be met in order to consider this piece of work a success)

### **User stories**

(How the product should work for various user types)

- 

### **Scope**

(Aspects of this work that are to be considered as **current** requirements)

### **Future work**

(Aspects of this work that are to be considered as **future** requirements)

**Tickets to be raised in Zenhub:**

- [x]  Update copy: Applicant to Informant
    - Find a replace all instances of Applicant and replace with Informant
    

- [x]  Update copy: Application to Declaration
    - Update all instance of application to declaration
    

- [x]  Update birth informant list
    
    Update list of informants to:
    Mother
    Father
    Grandfather
    Grandmother
    Brother
    Sister
    Legal Guardian
    Someone else
    
    Remove Mother & Father option
    https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/00.OpenCRVS-Specifications?node-id=1968%3A38017

    Remove Primary contact page if Mother & Father is chosen
    Remove additional someone else list page
    If someone else. Ask Relationship to child
    

- [x]  Update main point of contact list
    
    List of contacts should be the same as Informant list
    
    Mother
    Father
    Grandfather
    Grandmother
    Brother
    Sister
    Legal Guardian
    Someone else
    
    On selection ask for the phone number
    If someone else ask for phone number
    https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/00.OpenCRVS-Specifications?node-id=1968%3A39031

- [ ]  Remove default answer in declaration forms
         Remove marital status default answer.
   

- [ ]  Update default declaration questions and order
    Remove Social Security question
    Remove heritage questions form birth and death declaration form
    Ensure order is consistent between Child Mother Father Applicant Deceased

- [ ] Update Do you have the fathers details to a checkbox 

**Death**

[Death application](https://www.notion.so/Death-application-ada99eb56011418b9a8e1cc30c8f519c)

- [ ]  Create one list for applicant types (combine someone else list) 
 - If someone else ask for relationship to deceased on same page https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/00.OpenCRVS-Specifications?node-id=1968%3A39634
- [ ]  Reorder deceased and applicant questions to be consistent
- [ ] combine event details into one page https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/00.OpenCRVS-Specifications?node-id=1968%3A39545
- [ ]  Remove Social security question
