### ISSUE TITLE
Configure login background

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#2667]
https://www.notion.so/opencrvs/7d321101427640088c305b8bf630aa21?v=cd71becb0d0e4c14a13e67ba38fba1ac&p=fe95a9f4e4a54d628e4c7e943cbd684d&pm=s

### Description
- adds app background config option in Application config
- updates background. On Login, 2factor, Pin creation, Pin entry
- can select from any colours
- user can upload a background image
- user can select to fill the page with the image
- user can select to tile the image and select the tile size

### Acceptance Criteria
GIVEN I am a National System Admin
WHEN I am on Application config
THEN I can see the current config setting for the Login background

GIVEN I am a National System Admin
WHEN I select change
THEN show the login background model

GIVEN I enter a HEX code
WHEN I select apply
THEN update the login background to the new colour

GIVEN I upload a new image
WHEN I select apply
THEN update the login background to the new image

GIVEN I upload a new image
WHEN I select delete
THEN update the login background to the current colour HEX. 

....

### Design
https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=7014%3A133933

Backend tasks
- [x] Amend the [ApplicationConfigurationInput](https://github.com/opencrvs/opencrvs-core/blob/4299e59b6321ce6170c31ef0545e39245938c25a/packages/gateway/src/features/application/schema.graphql#L100) to include LOGIN_BACKGROUND and Amend the ApplicationConfiguration type to return it as well
```ts
enum ImageFit {
  FILL
  TILE
}

input LoginBackgroundInput {
  backgroundColor: string
  backgroundImage: string
  imageFit: ImageFit
}

type LoginBackground {
  backgroundColor: string
  backgroundImage: string
  imageFit: ImageFit
}
```
- [x] Update the `updateApplicationConfig` root-resolver and IApplicationConfigurationModel in config microservice accordingly. - 2

Frontend tasks
- [x] In src/views/sysadmin/config/application/mutations.ts include `LoginBackground ` in the return value for the query. Amend the `IApplicationConfig ` interface in referenceApi.ts to include the LOGIN_BACKGROUND property.
- [x] Create a component similar to `GovtLogo` inside src/views/sysadmin/config/application/generalProperties called `LoginBackground ` which uses the LOGIN_BACKGROUND property of offlineCountryConfiguration to render the loginBackground row according to the design. Render this component from `GeneralTabContent`.  - 1
- [x] Clicking change should open up a modal with 2 tabs -> Color & Image. For the color tab style the `TextInput` to have a smaller width and connect this with the canvas next to it which changes color according to hexvalue typed in the input. Validate the hex value using this regex: `"^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$"` - 2
- [x] For the Image tab, take the image as input similar to how it's done for the `GovernmentLogo`. Use the `Select2` component to render the select with the options Fill and Tile. By default it should be set to Fill - 1
- [x] Clicking Apply in the modal should call the function `callApplicationConfigMutation` similar to the other configuration flows(for example `govtLogoMutationHandler`). Handle the success and error states appropriately. - 1

**Comment by anny320** [comment]
@jpye-finch please advise on this ticket

**Comment by euanmillar** [comment]
Awaiting design

**Comment by euanmillar** [comment]
@jpye-finch @anny320 can we move this to Designed Product Features?  Looks fine to me

**Comment by Zangetsu101** [comment]
@jpye-finch Could you explain a bit about the values of these 2 selects please?
![image](https://user-images.githubusercontent.com/29002716/203113003-53fc90a2-10f5-4875-bd2b-eaf6c05b1baf.png)
The most relevant one for the values of the left select I found was the `objectFit` css property which takes these `fill | contain | cover | none | scale-down` values. I have no idea what the percentage value is for tho

**Comment by euanmillar** [comment]
In order to make the calculation work, we need a default pixel width and height value for the 100% tile.  Plus we need the options for the select.  Then we can divide / multiply down or up appropriately

**Comment by jpye-finch** [comment]
Lets go with 64x64px for default tile widths

**Comment by jpye-finch** [comment]
Suggest percentage becomes a number input. So uses can enter any percentage
<img width="354" alt="image" src="https://user-images.githubusercontent.com/46478402/203314374-7a8f5e2f-ff85-4e45-9259-ec369d3f5e8a.png">

**Comment by euanmillar** [comment]
Its going to be hard to preview the effect of this in the admin interface.  Plus allowing the user to enter any value could scale it as large as just a single background image would be in reality

**Comment by jpye-finch** [comment]
Yep reviewing will be annoying. Bit of back and forth. Could add a preview button as an improvement.

**Comment by jpye-finch** [comment]
Yep that is a possibility. but will need to allow them to enter 500-1000% if the default is 64x64px. The Zambia pattern used was 400x400 I believe.

**Comment by euanmillar** [comment]
Why dont we make our tile 400 x 400px and just allow the following options: 25%, 50%, 100%, 200%.  Anything above is a full screen image

**Comment by SyedaAfrida** [comment]
@jpye-finch Is there any fixed file type and file size for background image?

**Comment by jpye-finch** [comment]
good question. nothing was specified in the design... so no. But ideally countries are choosing small files to reduce loading time

**Comment by cinojopencrvs** [comment]
@anny320 - can we close this?
