### ISSUE TITLE
As a system admin I want to add a custom text input / area question

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2728]
### Description

- adds options to add default [questions/content to RightSideMenu default state](https://www.figma.com/file/pyp3KyEVRMjkmK2ye2iT9W/Configuration?node-id=1090%3A17678)
- OnAdd place element to bottom of page
- OnAdd change state to Active
- OnAdd [update RightSideMenu to config options for element](https://www.figma.com/file/pyp3KyEVRMjkmK2ye2iT9W/Configuration?node-id=1099%3A40903)
- Disable SaveButton until all mandatory fields have been completed

**RightSideMenu Config options**
- [TextInput config options ](https://www.figma.com/file/pyp3KyEVRMjkmK2ye2iT9W/Configuration?node-id=1099%3A48065)
-[ TextArea config options ](https://www.figma.com/file/pyp3KyEVRMjkmK2ye2iT9W/Configuration?node-id=1099%3A49390)
- [NumberInput](https://www.figma.com/file/pyp3KyEVRMjkmK2ye2iT9W/Configuration?node-id=1099%3A50665)

**More than 1 language**
- Add change language SelectButton
- OnChange of language. [Update RightSideMenu to show form content for the other language](https://www.figma.com/file/pyp3KyEVRMjkmK2ye2iT9W/Configuration?node-id=1099%3A75726)

### Acceptance criteria

GIVEN
WHEN
THEN

### Design
(Link to Figma)

### Tasks for text input

- [x] In FormTools create a sub view called CustomFieldForm.  Mark up the form using InputFields that contain an extra prop to use a smaller Font size and style, and add 2 Toggles at the top fr Hide field and Required - 2
- [x] At the bottom of the FormConfigCanvas, modify the draft on "add", populate an Element card with a custom field. It has a default label "Custom text input".  Default handlebar is customTextInput_1 or customTextInput_2, etc. depending on how many custom fields of this type are in this group.  The form element card should have the trash button enabled.  Populate the default handlebar in FormTools > CustomFieldForm with the new handlebar - 3
- [x] If the trash button is clicked, the custom field must be deleted from the draft - 1
- [x] We need a CustomFieldFormGenerator component: 

Get all available languages, if there is more than one language, duplicate all the fields, so that you have a field "label_en" & "label_fr" etc. Add a select outside of the Formik form to change languages.  The default language "English" should be selected and all fields associated with the default language should be visible.  However all fields, in all languages, must be validated whether visible or not.  The fields need a visible prop that will not interfere with Formik validation.  The form field type should update for custom text area, number, phone.  Submit button is disabled until all fields are valid. - 5

- [x] As the user types an English label, remove spaces and convert the string to camelCase in a function and update the handlebar: https://www.figma.com/file/pyp3KyEVRMjkmK2ye2iT9W/Configuration?node-id=1099%3A48065 - 1
- [x] On submit, gather all the data for the custom field from the formik form, along with the Toggle selections for Hide / Required and update the form draft to include the custom question, and update the Canvas to show any amends to Label, Placeholder, Required.

- fieldId should be in the format event.sectionId.groupId.fieldName where fieldName is the handlebar
- enabled should be set to a string "DISABLED" if the hide field toggle is on and empty if it is off.

If the custom handlbar ie the fieldName already exists, then do not update the draft, instead throw an error and show a validation error in the form "Sorry that certificate handlebar already exists. Please change the English label." - 3

- [x] Editing an existing custom question .... If you click an existing custom question, populate the form with initialValues from the draft custom question - 2
- [x] Closing without saving .... If you click anywhere else on the canvas, you close the existing CustomFieldForm and either open the default view for FormTools, or the CustomFieldForm for another custom field, or the DefaultFieldTools component for non-custom fields. - 2

**Comment by euanmillar** [comment]
Waiting for @Zangetsu101

**Comment by SyedaAfrida** [comment]
@anny320 the testcase for form config is updated and tested. so this ticket can be closed

**Comment by anny320** [comment]
completed
