### ISSUE TITLE
Deduplicate flow update

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#3112]
### Description

- updates deduplication flow
- In workqueue, review button should not go to exisitng broken comparison view, it should to the review page like any other review button ... ie removes comparison screen
- uses Alert component to show potential duplicates. On Record audit page and Declaration review page
- Alert comp used to show which records are potential duplicate with Tracking ID link
- logic remains the same

### Acceptance criteria

GIVEN a record is a potential duplicate
WHEN on the workqueue
THEN [show the duplicate icon](https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=5977%3A113160)

GIVEN a record is a potential duplicate
WHEN on click Review
THEN navigate to the [Review page and show the potential duplicates. ](https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=5977%3A116105)

GIVEN a record is a potential duplicate
WHEN on the Record Audit
THEN [show potential duplicates](https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=5977%3A113963)

### Design
https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=5977%3A113160

### Dev-tasks
- [ ]  Refactor out the duplicate comparison screens, instead Review button goes to review page.
- [ ] On Record Audit page show warning component - duplicated if more than one duplicate.  TrackingID info is in the graphql response.
- [ ] On the Review page show the same duplicate warnings as per the Figma design

**Comment by euanmillar** [comment]
Will aslo resolve: https://github.com/opencrvs/opencrvs-core/issues/3085

**Comment by Fariha-Amin** [comment]
@anny320 passed, can be closed

**Retest SS:**
![d](https://user-images.githubusercontent.com/105624748/173347373-d1503043-6c98-43f9-a0cf-c939275b26fa.PNG)
![dd](https://user-images.githubusercontent.com/105624748/173347378-6293d6b8-0199-43cc-bcd5-58eb7a001347.PNG)
![ddd](https://user-images.githubusercontent.com/105624748/173347384-15afc78e-f753-4195-889c-dd52de9bf35b.PNG)

**Comment by anny320** [comment]
completed
