### ISSUE TITLE
Health System Integration (v2)

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#3588]
### **Problem statement**
The current Health notification, is a hack payload from a legacy DHIS2 that doesnt support FHIR.

The payload must be changed into a FHIR standard bundle.  It has to contain the same composition as we create for a very basic birth declaration with as minimal data as possible.  

Mothers name
contactPhoneNumber
ChildDOB
eventLocationID

We should accept any other supported data for a full declaration.

It will need to be a new system client called "Health Notification".  Protected by JWT scope for that client.

Any legacy code such as the method which takes the name of a eventLocation and searches FHIR to find the id must be deprecated.

We could remove this code entierely from Farajaland, expose through Gateway with Swagger.

If we use some generic FHIR validation functions then we can re-use them.  Could we use OpenHIM as a FHIR validator?

We would also need to change the data-generator.

There are 2 bugs linked to this which need investigation and either closing due to legacy requirements or addressing.

We need a Postman Collection for this.

- [x] Create a new route in gateway with scope set to 'declare' and 'notification-api' that takes a fhir bundle as input posts it using this [function](https://github.com/opencrvs/opencrvs-core/blob/64ac4f1bdf823d19b7a23794b92fd1815b8c55cc/packages/gateway/src/features/fhir/utils.ts#L1020).
- [x] Before forwarding, we need to find the `Task` resource in the bundle and make sure the status is `draft`. This is because we check for the `draft` status in workflow to identify a bundle as an IN_PROGRESS declaration. Another one we need to check is that the task references the composition that's in the bundle properly. - 3
- [x] Create Postman collections for Birth and Death events that uses this endpoint to create hospital notifications. Add an example with the event location as a facility. We would like to create these declarations with all the details filled for reference. We would also need an example with minimum data as well - 2
- [x] Remove the `dhis2-notification` endpoint that we have in farajaland
- [x] Amend the data-generator to use the newly created endpoint to create hospital notifications - 1
- [ ] Some changes might be needed after the integrations epic

**Comment by euanmillar** [comment]
In my view, no design is required for this. We are just deprecating the old custom DHIS2 payload and how it is handled in favour of FHIR.

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed

https://user-images.githubusercontent.com/94350336/209629217-89eec342-b428-4752-bcff-ffe7132598ac.mp4
