### ISSUE TITLE
Migration approach for breaking changes and upgrading OpenCRVS

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#3709]
Implementers need a safe way to upgrade between OpenCRVS versions.  When a change request is classified by the Change Advisory Board as substantial, it usually involves a “breaking change”. 

Essentially this means that the previous installation process or database change required in order to enable the feature, means that it is no longer easy for a system administrator to update OpenCRVS to the new version.

So a breaking change can include:

- Database changes
- Installation changes
- Configuration changes
- Interoperability API changes

OpenSource DPGs provide various levels of service for breaking changes from basic documentation to automated tools.

Successful migration development and quality assurance requires test environments that contain snapshots of production test data.
Before QA of the migration can begin, the test data sets must apply to known behaviours that can be affected by the migration. These must be documented in the Issue. DevOps investment is required:

- QA environment works with latest v2.0 data for standard QA process.
- Config environment could become the Migration QA environment.  QA team must write test cases following documentation to migrate the config environment from v1 - v2 for example. 
- QA team must reset and import test data as per v1.0 using a DevOps Github Action, followed by sequential running of automated migration update instructions, updating the environment from v1 to v2 following the documentation.
- After v2 migration the QA test cases must check backwards compatibility of the new feature.  Bugs may be raised requiring more change requests that have been missed in design, dev or by the CAB.

- [ ] Write a migration script for a bug
- [ ] Prepare documentation for upgrading OpenCRVS Core - upgrade notes v1.0.1 - v.1.0.2
- [ ] Prepare documentation for upgrading OpenCRVS Farajaland - upgrade notes v1.0.1 - v.1.0.2
- [ ] In production environment, we must create a registration and an in progress application that has the mistake in legal guardian proof before we make a backup for QA migration test
- [ ] Save the version in localStorage that we have in the column in the left.  When the app loads initially, compare the version loaded with the version in localStorage. If the version is different empty all applications in indexedDB
- [ ] Run the emergency-backup script on production using config server IP to be the backup server.  SSH into config and label the backups as v1.0.1.  Maybe a custom shell script
- [ ] Write a github action to revert to a previous version: clears the database on config, restores OpenCRVS to an earlier version, and restores earlier version data so that QA team can replicate the migration tests
- [ ] Write a github action to upgrade versions from one to another: upgrade a previous version on config, and runs any upgrade commands.

**Comment by Zangetsu101** [comment]
@euanmillar instead of saving version in localStorage, we can instead use IndexedDB version that can passed when configuring localForage. For example, if previously we were using version 1, and in the next release we can change it to 2 which will make IndexedDB fire an event called `onupgradeneeded`. In the handler we can then remove all the drafts. Similar to: https://stackoverflow.com/a/34324949
