### ISSUE TITLE
Backend robustness

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#3711]
Description

We want to improve the robustness of the backend ...

For example: If a 3rd party service fails (e.g. if the country configuration package goes down) there is a problem: When registering, we validate a BRN / DRN via the countryconfig service. If there is a problem in that service and the request fails  then the declaration is in limbo. The declaration remains in a "waiting for validation" state.  There is no resolution to this and the declaration becomes lost in the system if the country has not enabled that work queue.

Essentially not every potential Data write is entirely visibly from a system monitoring point of view.
So, there a re a number of 3rd party dependencies such as the country configuration package or SMS notification service and there should be a way to re-run the transactions.  

In OpenHIM this is possible, but we have not documented how to do this, nor have we architected OpenCRVS so that every single data manipulation is re-runnable in OpenHIM. We have sometimes decided that requests from OpenHIM Channel to search happen asynchronously to requests to the contyconfig service.  This is a problem because search writes can happen at the wrong time, or get lost. 

Can these vulnerability be improved along with making more parts of the backend more robust in case of failure?

Can and should we introduce a different message bus, e.g. RabbitMQ, Kafka or similar? 

What problem are we trying to solve?  Is it to create event-driven microservices that can be logged effectively and supporting rolling back an event?  

How real is this issue at the moment?   

We need to list fragile parts of the application then decide what to do.

**Must refactor spaghetti code!!**

We need a visualisation of all the backend processes for all write events:  NOTIFICATION, DECLARATION, VALIDATION, REGISTRATION, REJECTION, CERTIFICATION, CORRECTION.

- [ ] We need a detailed sequence diagram for all write events

- [ ] We need to document how we are using OpenHIM and Hearth with FHIR.  If you look at docker compose, you see a constant FHIR_URL and HEARTH_URL - FHIR_URL makes no sense.  It should be OPENHIM_URL.  So there us tech debt when using this naming convention, and we need to know why and how these URLs are being.  If its a read from Hearth it is not a problem, but if it's a write to Hearth, then when writing stuff we should go through OpenHIM.

- [ ] OpenHIM has a message queue feature.  Should be using it more often?  Rabbit MQ and Kafka are complex, perhaps we can use OpenHIM.

- [x] We need to improve our integration between the client and services.  Currently auth, confiog, countryconfig and gateway are exposed externally. As is api.  It doesnt need to be.  We need to remove what we dont need from being publically exposed as scraping robots are filling up OpenHIM with trash.  We could create a new gateway microservice, every request is sorted and sent to either auth, or config or current graphql gateway so that we only have one entry point which easily whitelist
