### ISSUE TITLE
Component / <Icon>

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#3756]
Icons have been added adhock to date. Creating inconsistencies in how props like colour and size are applied. 

We use featherIcons for most Icons. With a few customised ones that are filled. Plus our Form Icons
https://www.figma.com/file/SsqCzO2eherXXCKyixmli9/OpenCRVS-Design-System-v2-WIP?node-id=1%3A2

This ticket is create a template component (further tickets will be raised to refactor existing icons):
- Uses a feather icon (https://feathericons.com/).
- Color prop: any colour from colour.ts
- Size prop
- Stroke with 2px (large icons) or 1.5px (small icons)
- Remove obsolete icons

Good example: https://dcos-labs.github.io/ui-kit/?path=/docs/graphic-elements-icon--default

https://github.com/supabase/ui/blob/master/src/components/Icon/Icon.tsx

### Storybook
Could we use the IconGallery. To make it loo more presentable?
https://storybook.js.org/docs/react/writing-docs/doc-block-icongallery

### Delete
ArrowWithGradient
BackArrow (replace with ArrowBack BackArrowDeepBlue (replace with ArrowBack)
ForwardArrowDeepBlue (replace with ArrowForward)
DeclarationsOrangeAmber
DisabledArrow
DraftSimple
Error
HeaderLogo
LogoutNavigation??
MinusTransparent
NoWifi
NotificationError
Outbox
Plus
Search
StatusCertified
StatusCollected
StatusGray
StatusGreen
StatusOrange
StatusProgress
StatusRejected
StatusWaitingValidation
Success
SystemBlack
SystemBlue
ThreeDots
Validate

### Notes:
MapPin small version of Location
SearchBlue v SearchDark
CrossLarge = Cross 

### Tasks
- [x] Create template component
- [x] Identify obsolete icons @jpye-finch 
- [x] Remove obsolete icons

**Comment by euanmillar** [comment]
@jpye-finch @Zangetsu101 needs to ask you a few things about this in order to move it forward.

**Comment by Zangetsu101** [comment]
Completed in #4055
