### ISSUE TITLE
As a National System Admin I want to configure the option to print in advance

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#4361]
### Description
- Updates Certificate config to add tabs for each event type
- Adds configuration option to allow printing in advance
- If false. Then the option 'Print in advance of collection and issuance' is not available
- If false. Then bulk printing is not available
- If false. Then there is no work-queue 'Ready to issue'

### Acceptance criteria

GIVEN I am a National System Admin
WHEN I toggle 'Allow printing in advanced of issuance' off
THEN hide the option 'Print in advance of collection and issuance'

GIVEN no event allows Printing off in advance
THEN hide the work-queue Ready to issue

### Design
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?node-id=10373%3A68429&t=4VbkamxwtyZTwWnj-1

### Front-End
- [x] Amend the Certificates configuration page for national system admin by separating the certificate templates into different tabs by event. - 2
- [x] Add a new options section in each tab with only the "Allow printing in advance of issuance" toggle settings -  1
### Back-End
- [x] Modify the ApplicationConfig model in config -> models -> config to include a "PRINT_IN_ADVANCE" option in both birth and death. In the mongoose schema use a default value of true which make it so that we won't need to run a migration. Update the handlers, Joi schema where needed.
- [x] Amend the updateApplicationConfig mutation as needed with the new option.
- [x] Amend the updateApplicationConfig mutation used in client to return the new value as well. Amend the IApplicationConfig type used throughout client - 3
### Merger
- [x] Connect the toggle button with the appropriate settings in application config - 1
- [x] Toggling the button would fire the mutation updateApplicationConfig with the BIRTH or DEATH property depending on the event - 1
- [x] In PrintCertificate -> CollectorForm, filter out the PRINT_IN_ADVANCE option depending on the configuration - 1

**Comment by SyedaAfrida** [comment]
@anny320 This ticket is fixed and can be closed

https://user-images.githubusercontent.com/94350336/224321649-01637868-b636-4946-b924-9a50943b8c71.mp4

**Comment by anny320** [comment]
completed
