### ISSUE TITLE
Application configuration for National ID:  MOSIP or OSIA

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#4559]
We need an application configuration setting to say if the National ID is a MOSIP integration, an OSIA integration or a custom integration.

- Adding a select to the National ID client creation. Options are:

“MOSIP”

“OSIA (coming soon)” - disabled

“OTHER”

Tech tasks

- [x] Amend "Select" component in component library. Add a "disabled" option to the options. React-select should be able to handle disabled options by default, but we don't have them in our component properties. - 1
- [x] Create an integratingSystemType of system modal which can be set to an enum. If NID is selected, then NIDIntegratingSystemType can be one of MOSIP, OSIA or OTHER
- [x] Add a Select into the integration creation modals, along with the information toast messages for each different system type (MOSIP, OSIA, other) with placeholders for supporting copy. The label is System and appears if the selected type is National ID.  Populate with 3 values from the NIDIntegratingSystemType enum, but disable OSIA with the coming soon message. - 2
- [x] Update gateway and user-mgnt (also check for config & webhooks) handlers to update and retrieve integratingSystemType where appropriate throughout the code wherever systems are used. - 2
- [x] In the worklfow service we check the integration [name](https://github.com/opencrvs/opencrvs-core/blob/92f2c27cb4a3e00db4602845a698300384c6acab/packages/workflow/src/features/registration/fhir/fhir-bundle-modifier.ts#L714) rather than the NID integration type in order to communicate with MOSIP.  Instead we can check the integratingSystemType which will be better. - 1
- [x] Migration for System model. If existing System name is "MOSIP" and type NATIONAL_ID, make `integratingSystemType` `MOSIP` - 1

<img width="289" alt="config - nid" src="https://user-images.githubusercontent.com/3169954/224667561-69748753-f8a9-4d72-999d-e375531f73ed.png">

- [ ] Block the ticket so that Euan can update the supporting copy
