### ISSUE TITLE
Capture verbal agreement of informant to submit declaration

### ISSUE THREAD

**Issue by naftis** [opencrvs/opencrvs-core#4939]
## Description

As a user, I need to get an approval from a declarant after the declaration process.
So that, the declarant can get his/her voice recorded as a signature at the end of declaration process.

Recommendation: Add voice recording capability from Nigeria instance

## Tasks

- [ ] Create design based on Nigeria implementation with JPF
- [ ] Create AC based on design
- [ ] Go through in tech design

## AC

TBC

GIVEN that I'm a field agent (or who?)
WHEN I'm on the declaration review page
THEN I'm able to sign by audio

## Dev tasks

**Note!** This feature has been partly implemented in Nigeria in this PR: https://github.com/opencrvs/opencrvs-core/pull/4484

- [ ] Copy the feature over from the existing PR
- [ ] Convert the feature to use Minio instead of saving the audio as base64 in Hearth in the record
- [ ] Add translations instead of hard coded English words
- [ ] (tests...?)
