### ISSUE TITLE
Refactor certificator collector and correction requester list options

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#5994]
We are not showing the correct options on:
- Certy record screen
- Issue record screen
- Correction requester screen

Some of the issue might just require copy updates. 

****Note.** Hiding the option mother or father IF their details were not avilable **is** working!**

Example bug:
Currently In this example the informant is the Grandfather. This is what we show on the Certify record screen. 
Instead of:  Print and issue to informant (Grandfather), Print and issue to mother, Print and issue to father
![Image](https://github.com/opencrvs/opencrvs-core/assets/46478402/2797c556-f41e-4dfa-ba74-b71fe55f7e19)

### Certify record required list:

**Birth:**
Print and issue to informant ([Relationship to child])
Print and issue to mother {IF details available AND not informant}
Print and issue to father {IF details available AND not informant}
Print and issue to somone else
Print in advance of issuance

_1. Copy update to remove (Informant) from mother and father options_
_2. Add informant option??!_

**Death:**
Print and issue to informant ([Relationship to deceased])
Print and issue to somone else
Print in advance of issuance

_1. Copy update to add Print and issue to informant_
_2. Add relationship to deceased in brackets_
_3. Add option to print in advance_

**Marriage:**
Print and issue to informant ([Informant type])
Print and issue to groom
Print and issue to bride
Print and issue to somone else
Print in advance of issuance

_1. Copy update to add Print and issue bride/groom_
_2. Add informant option_
_3. Add option to print in advance_

### Issue record required list:

**Birth:**
Issue to informant ([Relationship to child])
Issue to mother {IF details available AND not informant}
Issue to father {IF details available AND not informant}
Issue to somone else

_Working as expected_

**Death:**
Issue to informant ([Relationship to deceased])
Issue to somone else

**Marriage:**
Issue to informant ([Relationship to deceased])
Issue to groom
Issue to bride
Issue to somone else

### Correct record required list:

**Birth:**
We are missing the informant option with relationship to child

Informant ([Relationship to child])
Mother  {IF details available AND not informant}
Father {IF details available AND not informant}
Child
Another registration agent or field agent
Me
Court
Someone else

**Death:**
We don't have the relationship to the deceased in bracket

Informant ([Relationship to deceased])
Another registration agent or field agent
Me
Court
Me
Someone else

**Tasks**
- [x] Remove Other family member from Relationship to child dropdown
- [x] Update copy for Death list: "Informant" to Print and issue to informant ([Relationship to deceased])
- [x] Add option to Print and issue to informant ([Informant type]) for marriage
- [x] Update copy for bride and groom "Print and issue to bride", "Print and issue to groom"
...
...

**Comment by euanmillar** [comment]
Reminder: If using informants details on a death cert, you need to check informantType in a handlebar if conditional before accessing names of spouse or parents.

**Comment by euanmillar** [comment]
Is it a problem that there is no informantType relationship pointers for death?  I think this may require a migration: https://github.com/opencrvs/opencrvs-core/blob/45e93d40bb2714430eda9e6402a49530c0c33329/packages/gateway/src/features/registration/fhir-builders.ts#L867

**Comment by Nil20** [comment]
https://github.com/opencrvs/opencrvs-core/issues/5939

This ticket's issue should be fixed in this refactoring.

**Comment by SyedaAfrida** [comment]
**Bugs:**

- [ ] If the relationship to child/ deceased/ spouse is more than one word than "_" is shown between the words
![hyphen2](https://github.com/opencrvs/opencrvs-core/assets/94350336/a41b723a-7532-44d2-9f7f-07af706a5547)
![hyphen3](https://github.com/opencrvs/opencrvs-core/assets/94350336/07c2e8a7-d298-40ae-9a91-73d0434bfd43)

- [ ] In the corrected record modal (record audit> History), Informant relation is not shown properly
Note: It is working if the informant is mother/ father (birth declaration) bride/ groom (marriage declaration
![correction Req](https://github.com/opencrvs/opencrvs-core/assets/94350336/71cbddef-49fa-4ab4-b3fc-b0be0193e2ed)

**Comment by SyedaAfrida** [comment]
This bug is fixed
![marr](https://github.com/opencrvs/opencrvs-core/assets/94350336/13b0f19a-3e10-421d-8b5b-cc6f94449293)
![info](https://github.com/opencrvs/opencrvs-core/assets/94350336/37bea689-0766-4e57-ad1b-050d802e6fe2)
![death cor](https://github.com/opencrvs/opencrvs-core/assets/94350336/fa7ebcd5-3c81-4578-918b-717f50d21ca4)
![death df](https://github.com/opencrvs/opencrvs-core/assets/94350336/d1e3f9b8-3644-4daf-90f8-4d6f73cbb91c)
