### ISSUE TITLE
Refactor Verify ID page to be dynamic based on age and id fields in the form

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#6052]
We need to make the verify ID page dynamic based on what was captured in the form. This page is prompted in the workflows:
- Certify record
- Issue record 
- Correct record

Alwawys shown:
- Firstname(s)
- Lastname
- Date of birth
- Nationality @euanmillar ??

Dynamic:
- ID (type and number)
- Age

![Image](https://github.com/opencrvs/opencrvs-core/assets/46478402/d8ce3c49-d725-4beb-9235-e1e9f0c05db3)

**Tasks**
- [x] refactor logic of summary rows 
- [x] change Content title to "Verify their identity"
- [x] change CTA copy: "Identity verfied" and "Identity does not match"

**Comment by SyedaAfrida** [comment]
**Bug:**
When the informant is mother/ father in birth declaration and ID is also provided, then ID is not showing in Verify ID page 

https://github.com/opencrvs/opencrvs-core/assets/94350336/b887e9de-53b6-4894-b412-99744e6a744d

**Comment by Nil20** [comment]
https://github.com/opencrvs/opencrvs-core/pull/6106
This PR should fix this issue as well

**Comment by SyedaAfrida** [comment]
This bug is fixed

https://github.com/opencrvs/opencrvs-core/assets/94350336/aa4de4fc-9819-434a-9fba-9f39a2a83305
