### ISSUE TITLE
Robust registration confirmation, handle all possible scenarios 

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#6386]
There is a real chance any processing, including integrations to other government systems executed in country config's `/event-registration` might fail. If this happens, the record is indefinitely labelled as "WAITING_VALIDATION". Currently there's no way to recover from this error. 

## Requirements
- Core should implement and know how to handle all scenarios described in table below
- It should be possible for a record to be in WAITING_VALIDATION state as long as possible
- Country config's registration implementation cannot be trusted. If core doesn't get a confirmation from CC with a correct HTTP status, it's better to keep the record in the user's outbox.
- There should be a way of seeing, either technically or in a UI, the number of records waiting validation. Maybe even a function to resubmit a record awaiting validation. @jpye-finch this could even be the "Recent" workqueue.

## Open questions
- ~Should the receiving endpoint be idempotent?~
  - Probably too difficult for countries to implement properly
- ~"validation" feels like an incorrect term here as there's no recovery flow from an "invalid" record~
  - Record rejection should cover this case for now

## Record validation outcomes
<table>
<tr>
 <td>
 <td>Response status
 <td>End result
<tr>
 <td>Endpoint fails in uncontrolled manner
 <td>Non 2** or 4**  status
 <td>Record never leaves sender's outbox
<tr>
 <td>Synchronous flow failed
 <td>4** status
 <td>Record rejected
<tr>
 <td>Synchronous flow succeeded
 <td>200 status
 <td>Response payload read, treated internally same as async confirmation `/confirm/registration`
<tr>
 <td>Asynchronous flow assumed
 <td>202 status
 <td>Record stored in WAITING_VALIDATION workqueue
<tr>
 <td>Asynchronous flow succeeded
 <td>CC sends success payload to `/confirm/registration`
 <td>Record registered
<tr>
 <td>Asynchronous flow failed
 <td>CC sends fail payload to `/reject/registration`
 <td>Record rejected
</table>

## Tasks
- [ ] Create a test case for each registration confirmation outcome [Table 1]
- [ ] Create a /POST endpoint for each action `event.${action}.confirm` (or similar). [This will be called later when 202 is returned]. Endpoint sets `{confirmed: true}` for the event.
- [ ] Document breaking changes

**Comment by euanmillar** [comment]
@rikukissa I think this endpoint has been deprecated and I think that we can additionally deprecate the EXTERNAL_VALIDATION_WORKQUEUE setting and all code associated with those workqueues @jpye-finch .  They have never been used since Bangladesh.  We now have an /event-registration handler and any error there results in the record being rejected and visible in the rejected workqueue with a technical error message thanks to the boom throw.  Once the issue is resolved the record can be submitted.  https://github.com/opencrvs/opencrvs-countryconfig/blob/7be22de4d2bf8821329f5122e436958f7eff8872/src/api/event-registration/handler.ts#L48

Can this ticket be re-written to deprecate EXTERNAL_VALIDATION_WORKQUEUE and all UI code associated with that work queue instead?

**Comment by rikukissa** [comment]
@euanmillar description updated 👍

**Comment by euanmillar** [comment]
@rikukissa I think we need to remove the deprecation task related to ```EXTERNAL_VALIDATION_WORKQUEUE``` as @naftis is going to make use of it in the MOSIP integration after all.  I'm glad we didnt remove it earlier.

**Comment by rikukissa** [comment]
The `EXTERNAL_VALIDATION_WORKQUEUE` and everything related specifically to it will be removed as part of configurable workqueues task https://github.com/opencrvs/opencrvs-core/issues/7073. I'll leave it up to Pyry to decide, but as both are in 1.7 it might still make sense to remove everything related in this task

**Comment by naftis** [comment]
It should get removed as configurable workqueues can filter by `RegStatus.WaitingValidation`. For MOSIP integration, I'm not being blocked or having to write tech debty code, was it either way around.

**Comment by euanmillar** [comment]
@rikukissa @makelicious @naftis need to address this as part of custom events I believe.

**Comment by rikukissa** [comment]
Moving this under custom vital events epic

**Comment by rikukissa** [comment]
Closed in favour of https://github.com/opencrvs/opencrvs-core/issues/7850
