### ISSUE TITLE
Automatic decryption and mounting of encrypted partition on boot

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#6983]
Implement the first version of automatically opened disk encryption. Currently this is a completely manual, not-so-well-documented process. The impact of this is a much more reliable and easy to maintain server that is not critically affected for instance in the case of a power outage.

### Tasks

- [x] Ensure Docker is not started automatically when server starts
- [ ] Capture user's Github token on environment creation and store in a Github Secret. Change the documentation for creating this token to say that it also needs privileges to perform a repository dispatch action.
- [ ] Create a new Github actions pipeline to country config that decrypts and mounts the encrypted partition via SSH. [Farajaland implementation](https://github.com/opencrvs/opencrvs-farajaland/actions/workflows/restart-droplet.yml) can be used as inspiration. This pipeline needs to be possible to also be triggered with a repository dispatch.
- [ ] Configure all servers to make an HTTP request on boot to this pipeline. The pipeline should then kick in and decrypt the drive.
- [ ] Ensure infrastructure and networking documentation instructs countries that they need to have egress from the server to Github
- [ ] In pre-deployment checklist document add a new entry to test that rebooting works consistently

**Comment by rikukissa** [comment]
Related https://github.com/opencrvs/opencrvs-core/issues/6346

**Comment by adskyiproger** [comment]
Step 1: Create an Override File
Run the following command to open an override file for Docker:

bash
Copy
Edit
sudo systemctl edit docker.service
This will open an empty editor where you can define only the changes you want to apply.

Step 2: Add Your Customizations
For example, if you want Docker to start only after my-service.service has executed, add this content:

ini
Copy
Edit
[Unit]
After=my-service.service
Requires=my-service.service
If you need to add custom startup options for Docker, modify the ExecStart like this:

ini
Copy
Edit
[Service]
ExecStart=
ExecStart=/usr/bin/dockerd --your-custom-flags
The first ExecStart= clears the existing command before redefining it.

Step 3: Apply the Changes
After saving the override file, reload systemd:

bash
Copy
Edit
sudo systemctl daemon-reload
sudo systemctl restart docker
Step 4: Verify the Customization
Check that Docker is now dependent on my-service.service:

bash
Copy
Edit
systemctl cat docker.service
This will show both the original service file and your override.

To check dependencies:

bash
Copy
Edit
systemctl list-dependencies docker.service
Why Use Overrides?
✅ Preserves changes across updates
✅ No need to modify package-managed files
✅ Easy to revert changes by running sudo systemctl revert docker.service

Would you like additional customizations, like a delayed start or environment variables? 🚀

**Comment by adskyiproger** [comment]
We could use systemd overrides for that.
