### ISSUE TITLE
MOSIP country configuration deployment

### ISSUE THREAD

**Issue by naftis** [opencrvs/opencrvs-core#7911]
Depends on https://github.com/opencrvs/opencrvs-countryconfig/pull/288

### Motivation

We need a way to show how the MOSIP is configured and deployed.

### Dev tasks

Create a branch and pull request to `opencrvs-countryconfig`, using the [opencrvs/mosip](https://github.com/opencrvs/mosip) repository installation guide. Use `yarn add @opencrvs/mosip` to add the package. Test it locally and if you need to do amends to `opencrvs/mosip` repository, use `yarn link` to develop the integration.

Then, add the MOSIP, and the mosip-mock server to the infrastructure in country-config [docker-compose.yml](https://github.com/opencrvs/opencrvs-countryconfig/blob/develop/infrastructure/docker-compose.deploy.yml). You can ask one of our devops team (Shoumik, Niko, Jamil, Riku) to help with this task.

We can separate this to it's own repository, but lets start with the countryconfig branch.

### Definition of done

* A pull request to opencrvs-countryconfig that has `@opencrvs/mosip` as an installed package
* The form configuration has something imported from `@opencrvs/mosip` - it can be only a "MOSIP Enabled ✔ " paragraph for example
* The [@opencrvs/mosip/server](https://github.com/opencrvs/mosip/tree/main/packages/server) is deployed within the stack.
* The [@opencrvs/mosip/mosip-mock](https://github.com/opencrvs/mosip/tree/main/packages/mosip-mock) is deployed within the stack.
* A E2E URL to see the stack working

**Comment by naftis** [comment]
Currently I have made it so that https://github.com/opencrvs/e2e/ can be deployed using the "mosip" branch. With a stack name "mosip" it deploys to https://mosip.opencrvs.dev

## To-do

- [ ] Make it so that pull requests to the MOSIP repository are automatically deployed to their own environment
- [ ] ...or add a simple github action to deploy from the MOSIP repository
- [ ] Documentate our deployment environments (Collab, MEC)

**Comment by naftis** [comment]
https://github.com/opencrvs/opencrvs-countryconfig-mosip-dev
The deployment country-config is handled here. Currently the registrations are going to requires updates. Looking into it.
